export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_ERROR = 'VERIFY_EMAIL';
export const GET_USER = 'GET_USER';

export const UPDATE_AUCTIONS = 'UPDATE_AUCTIONS';

export const UPDATE_ITEMS = 'UPDATE_ITEMS';

export const GET_PREFERENCE = 'GET_PREFERENCE';
export const SET_PREFERENCE_LOCAL = 'SET_PREFERENCE_LOCAL';
export const SET_PREFERENCE_REMOTE = 'SET_PREFERENCE_REMOTE';
